version: '3.8'

services:
  db:
    image: postgres:13.12-alpine
    environment:
      POSTGRES_DB: cinefinder
      POSTGRES_USER: cinefinder
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
